// <auto-generated />
using System;
using GeoServ.Api.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GeoServ.Api.Migrations
{
    [DbContext(typeof(GeoServDbContext))]
    [Migration("20260827150248_AddConsumablesAndFixedCostsHeader")]
    partial class AddConsumablesAndFixedCostsHeader
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GeoServ.Api.Domain.Entities.AccountingMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid?>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CheckId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("DirectCostId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FinancialAccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FixedCostId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsIncome")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("PaymentMethodId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RegisteredByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ResponsibleId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ServiceOrderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CheckId");

                    b.HasIndex("DirectCostId");

                    b.HasIndex("FinancialAccountId");

                    b.HasIndex("FixedCostId");

                    b.HasIndex("PaymentMethodId");

                    b.HasIndex("RegisteredByUserId");

                    b.HasIndex("ResponsibleId");

                    b.HasIndex("ServiceOrderId");

                    b.ToTable("AccountingMovements");
                });

            modelBuilder.Entity("GeoServ.Api.Domain.Entities.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ProviderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PurchasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("UsefulLifeMonths")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("GeoServ.Api.Domain.Entities.Check", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CheckNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IssuerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observations")
                        .HasColumnType("text");

                    b.Property<Guid?>("ReceivedFromClientId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReceivedFromClientId");

                    b.ToTable("Checks");
                });

            modelBuilder.Entity("GeoServ.Api.Domain.Entities.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("CompanyTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TaxId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompanyTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("GeoServ.Api.Domain.Entities.CompanyType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CompanyTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d1111111-1111-1111-1111-111111111111"),
                            Name = "Proyecto Minero"
                        },
                        new
                        {
                            Id = new Guid("d2222222-2222-2222-2222-222222222222"),
                            Name = "Consultora Minera"
                        },
                        new
                        {
                            Id = new Guid("d3333333-3333-3333-3333-333333333333"),
                            Name = "Contratista Minero"
                        },
                        new
                        {
                            Id = new Guid("d4444444-4444-4444-4444-444444444444"),
                            Name = "Establecimiento Gubernamental"
                        },
                        new
                        {
                            Id = new Guid("d5555555-5555-5555-5555-555555555555"),
                            Name = "Académico / Universitario"
                        },
                        new
                        {
                            Id = new Guid("d6666666-6666-6666-6666-666666666666"),
                            Name = "Particular / Inversionista"
                        },
                        new
                        {
                            Id = new Guid("d8888888-8888-8888-8888-888888888888"),
                            Name = "Compañía Minera"
                        },
                        new
                        {
                            Id = new Guid("d7777777-7777-7777-7777-777777777777"),
                            Name = "Otro"
                        });
                });

            modelBuilder.Entity("GeoServ.Api.Domain.Entities.Consumable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConsumableClassId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observation")
                        .HasColumnType("text");

                    b.Property<Guid?>("ProviderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TotalCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("UnitCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ConsumableClassId");

                    b.HasIndex("ProviderId");

                    b.HasIndex("UnitId");

                    b.ToTable("Consumables");
                });

            modelBuilder.Entity("GeoServ.Api.Domain.Entities.ConsumableClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConsumableTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ConsumableTypeId");

                    b.ToTable("ConsumableClasses");
                });

            modelBuilder.Entity("GeoServ.Api.Domain.Entities.ConsumableType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ConsumableTypes");
                });

            modelBuilder.Entity("GeoServ.Api.Domain.Entities.Currency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Currencies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f1111111-1111-1111-1111-111111111111"),
                            Code = "ARS",
                            IsActive = true,
                            Name = "Peso Argentino",
                            Symbol = "$"
                        },
                        new
                        {
                            Id = new Guid("f2222222-2222-2222-2222-222222222222"),
                            Code = "USD",
                            IsActive = true,
                            Name = "Dólar Estadounidense",
                            Symbol = "U$D"
                        },
                        new
                        {
                            Id = new Guid("f3333333-3333-3333-3333-333333333333"),
                            Code = "CLP",
                            IsActive = true,
                            Name = "Peso Chileno",
                            Symbol = "$"
                        });
                });

            modelBuilder.Entity("GeoServ.Api.Domain.Entities.DirectCost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observations")
                        .HasColumnType("text");

                    b.Property<Guid?>("PaidById")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PaymentMethodId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProviderId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("RegisteredByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ServiceOrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid?>("UnitId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PaidById");

                    b.HasIndex("PaymentMethodId");

                    b.HasIndex("ProviderId");

                    b.HasIndex("RegisteredByUserId");

                    b.HasIndex("ServiceOrderId");

                    b.HasIndex("UnitId");

                    b.ToTable("DirectCosts");
                });

            modelBuilder.Entity("GeoServ.Api.Domain.Entities.DirectCostCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DirectCostCategories");
                });

            modelBuilder.Entity("GeoServ.Api.Domain.Entities.DistributionConcept", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DistributionConcepts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e1111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            Name = "Amortización Gastos"
                        },
                        new
                        {
                            Id = new Guid("e2222222-2222-2222-2222-222222222222"),
                            IsActive = true,
                            Name = "Capitalización"
                        },
                        new
                        {
                            Id = new Guid("e3333333-3333-3333-3333-333333333333"),
                            IsActive = true,
                            Name = "Honorarios"
                        },
                        new
                        {
                            Id = new Guid("e4444444-4444-4444-4444-444444444444"),
                            IsActive = true,
                            Name = "Utilidad"
                        });
                });

            modelBuilder.Entity("GeoServ.Api.Domain.Entities.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LogoSvg")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Subdominio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TaxId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("GeoServ.Api.Domain.Entities.EmpresaConfiguracion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ValueType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Key")
                        .IsUnique();

                    b.ToTable("EmpresaConfiguraciones");
                });

            modelBuilder.Entity("GeoServ.Api.Domain.Entities.FinancialAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.ToTable("FinancialAccounts");
                });

            modelBuilder.Entity("GeoServ.Api.Domain.Entities.FixedCost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("FixedCosts");
                });

            modelBuilder.Entity("GeoServ.Api.Domain.Entities.FixedCostCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FixedCostCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1111111-1111-1111-1111-111111111111"),
                            Description = "Pagos de alquiler de oficina o locales",
                            Name = "Alquileres"
                        },
                        new
                        {
                            Id = new Guid("c2222222-2222-2222-2222-222222222222"),
                            Description = "Nómina de empleados fijos",
                            Name = "Sueldos y Cargas Sociales"
                        },
                        new
                        {
                            Id = new Guid("c3333333-3333-3333-3333-333333333333"),
                            Description = "Luz, agua, internet, telefonía",
                            Name = "Servicios Básicos"
                        },
                        new
                        {
                            Id = new Guid("c4444444-4444-4444-4444-444444444444"),
                            Description = "Suscripciones, licencias, hosting",
                            Name = "Software e IT"
                        },
                        new
                        {
                            Id = new Guid("c5555555-5555-5555-5555-555555555555"),
                            Description = "Tasas municipales, seguros de responsabilidad, etc.",
                            Name = "Impuestos y Seguros"
                        },
                        new
                        {
                            Id = new Guid("c6666666-6666-6666-6666-666666666666"),
                            Description = "Contadores, abogados (fijos)",
                            Name = "Honorarios Profesionales"
                        });
                });

            modelBuilder.Entity("GeoServ.Api.Domain.Entities.FixedCostItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("InitialAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observation")
                        .HasColumnType("text");

                    b.Property<Guid?>("ProviderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ProviderId");

                    b.ToTable("FixedCostItems");
                });

            modelBuilder.Entity("GeoServ.Api.Domain.Entities.FixedCostPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FixedCostItemId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PaymentMethodId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReceiptNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FixedCostItemId");

                    b.HasIndex("PaymentMethodId");

                    b.ToTable("FixedCostPayments");
                });

            modelBuilder.Entity("GeoServ.Api.Domain.Entities.MovementCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsIncome")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MovementCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-111111111111"),
                            Description = "Ingreso por trabajos realizados",
                            IsActive = true,
                            IsIncome = true,
                            Name = "Cobro de Orden de Servicio"
                        },
                        new
                        {
                            Id = new Guid("a2222222-2222-2222-2222-222222222222"),
                            Description = "Ingreso de fondos por cheque",
                            IsActive = true,
                            IsIncome = true,
                            Name = "Acreditación de Cheque"
                        },
                        new
                        {
                            Id = new Guid("a3333333-3333-3333-3333-333333333333"),
                            Description = "Entrada de fondos desde otra cuenta propia",
                            IsActive = true,
                            IsIncome = true,
                            Name = "Transferencia Interna (Ingreso)"
                        },
                        new
                        {
                            Id = new Guid("a4444444-4444-4444-4444-444444444444"),
                            Description = "Ingreso por aportes de capital",
                            IsActive = true,
                            IsIncome = true,
                            Name = "Aporte de Socios / Capital"
                        },
                        new
                        {
                            Id = new Guid("a5555555-5555-5555-5555-555555555555"),
                            Description = "Ingreso por subsidios",
                            IsActive = true,
                            IsIncome = true,
                            Name = "Subsidio / Aporte Estatal"
                        },
                        new
                        {
                            Id = new Guid("a6666666-6666-6666-6666-666666666666"),
                            Description = "Luz, internet, alquiler",
                            IsActive = true,
                            IsIncome = false,
                            Name = "Pago de Gasto Fijo"
                        },
                        new
                        {
                            Id = new Guid("a7777777-7777-7777-7777-777777777777"),
                            Description = "Insumos para obras",
                            IsActive = true,
                            IsIncome = false,
                            Name = "Pago de Costo Directo"
                        },
                        new
                        {
                            Id = new Guid("a8888888-8888-8888-8888-888888888888"),
                            Description = "Equipamiento, rodados",
                            IsActive = true,
                            IsIncome = false,
                            Name = "Compra de Activo"
                        },
                        new
                        {
                            Id = new Guid("a9999999-9999-9999-9999-999999999999"),
                            Description = "Honorarios de socios o terceros",
                            IsActive = true,
                            IsIncome = false,
                            Name = "Pago de Honorarios"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Description = "Salida de fondos hacia otra cuenta propia",
                            IsActive = true,
                            IsIncome = false,
                            Name = "Transferencia Interna (Egreso)"
                        });
                });

            modelBuilder.Entity("GeoServ.Api.Domain.Entities.PaymentMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PaymentMethods");
                });

            modelBuilder.Entity("GeoServ.Api.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("GeoServ.Api.Domain.Entities.Provider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Providers");
                });

            modelBuilder.Entity("GeoServ.Api.Domain.Entities.Responsible", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Position")
                        .HasColumnType("text");

                    b.Property<string>("Specialties")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Responsibles");
                });

            modelBuilder.Entity("GeoServ.Api.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("GeoServ.Api.Domain.Entities.ServiceOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActualEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ActualStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("BudgetedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("BudgetedTasksDetail")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CanceledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CollectedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("CollectionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CurrencyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<decimal>("Discount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("EstimatedEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EstimatedStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("ExchangeRateAtBudget")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal?>("ExchangeRateAtCollection")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal?>("ForeignAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RequestDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ServiceTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("ProjectId");

                    b.HasIndex("ServiceTypeId");

                    b.HasIndex("StatusId");

                    b.ToTable("ServiceOrders");
                });

            modelBuilder.Entity("GeoServ.Api.Domain.Entities.ServiceOrderActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("LongDetail")
                        .HasColumnType("text");

                    b.Property<int>("ProgressPercentage")
                        .HasColumnType("integer");

                    b.Property<Guid>("ServiceOrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("ShortDetail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ServiceOrderId");

                    b.ToTable("ServiceOrderActivities");
                });

            modelBuilder.Entity("GeoServ.Api.Domain.Entities.ServiceOrderDistribution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("ActualAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("DistributionConceptId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ExpectedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Percentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<Guid>("ServiceOrderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DistributionConceptId");

                    b.HasIndex("ServiceOrderId");

                    b.ToTable("ServiceOrderDistributions");
                });

            modelBuilder.Entity("GeoServ.Api.Domain.Entities.ServiceOrderDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsVisibleToClient")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ServiceOrderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UploadedById")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ServiceOrderId");

                    b.HasIndex("UploadedById");

                    b.ToTable("ServiceOrderDocuments");
                });

            modelBuilder.Entity("GeoServ.Api.Domain.Entities.ServiceOrderObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ObservationType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ServiceOrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ServiceOrderId");

                    b.HasIndex("UserId");

                    b.ToTable("ServiceOrderObservations");
                });

            modelBuilder.Entity("GeoServ.Api.Domain.Entities.ServiceOrderResponsible", b =>
                {
                    b.Property<Guid>("ServiceOrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ResponsibleId")
                        .HasColumnType("uuid");

                    b.HasKey("ServiceOrderId", "ResponsibleId");

                    b.HasIndex("ResponsibleId");

                    b.ToTable("ServiceOrderResponsibles");
                });

            modelBuilder.Entity("GeoServ.Api.Domain.Entities.ServiceOrderStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ServiceOrderStatuses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-111111111111"),
                            Description = "Orden recién registrada",
                            Name = "Alta",
                            OrderIndex = 1
                        },
                        new
                        {
                            Id = new Guid("a2222222-2222-2222-2222-222222222222"),
                            Description = "Presupuesto enviado al cliente",
                            Name = "Presupuestada",
                            OrderIndex = 2
                        },
                        new
                        {
                            Id = new Guid("a3333333-3333-3333-3333-333333333333"),
                            Description = "Presupuesto aprobado por el cliente",
                            Name = "Aprobada",
                            OrderIndex = 3
                        },
                        new
                        {
                            Id = new Guid("a4444444-4444-4444-4444-444444444444"),
                            Description = "Trabajo en ejecución",
                            Name = "Iniciada",
                            OrderIndex = 4
                        },
                        new
                        {
                            Id = new Guid("a5555555-5555-5555-5555-555555555555"),
                            Description = "Trabajo entregado al cliente",
                            Name = "Entregada",
                            OrderIndex = 5
                        },
                        new
                        {
                            Id = new Guid("a6666666-6666-6666-6666-666666666666"),
                            Description = "Orden pagada en su totalidad",
                            Name = "Cobrada",
                            OrderIndex = 6
                        },
                        new
                        {
                            Id = new Guid("a7777777-7777-7777-7777-777777777777"),
                            Description = "Orden anulada o cancelada",
                            Name = "Cancelada",
                            OrderIndex = 7
                        });
                });

            modelBuilder.Entity("GeoServ.Api.Domain.Entities.ServiceType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ServiceTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1111111-1111-1111-1111-111111111111"),
                            Description = "Medición y representación gráfica del terreno",
                            Name = "Levantamiento Topográfico"
                        },
                        new
                        {
                            Id = new Guid("b2222222-2222-2222-2222-222222222222"),
                            Description = "Determinación de límites de propiedad",
                            Name = "Mensura"
                        },
                        new
                        {
                            Id = new Guid("b3333333-3333-3333-3333-333333333333"),
                            Description = "Posicionamiento de alta precisión",
                            Name = "Estudio Geodésico"
                        },
                        new
                        {
                            Id = new Guid("b4444444-4444-4444-4444-444444444444"),
                            Description = "Levantamiento mediante drones o imágenes satelitales",
                            Name = "Fotogrametría"
                        },
                        new
                        {
                            Id = new Guid("b5555555-5555-5555-5555-555555555555"),
                            Description = "Asesoramiento en proyectos de ingeniería",
                            Name = "Consultoría Técnica"
                        });
                });

            modelBuilder.Entity("GeoServ.Api.Domain.Entities.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("GeoServ.Api.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GeoServ.Api.Domain.Entities.AccountingMovement", b =>
                {
                    b.HasOne("GeoServ.Api.Domain.Entities.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId");

                    b.HasOne("GeoServ.Api.Domain.Entities.MovementCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GeoServ.Api.Domain.Entities.Check", "Check")
                        .WithMany()
                        .HasForeignKey("CheckId");

                    b.HasOne("GeoServ.Api.Domain.Entities.DirectCost", "DirectCost")
                        .WithMany()
                        .HasForeignKey("DirectCostId");

                    b.HasOne("GeoServ.Api.Domain.Entities.FinancialAccount", "FinancialAccount")
                        .WithMany()
                        .HasForeignKey("FinancialAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GeoServ.Api.Domain.Entities.FixedCost", "FixedCost")
                        .WithMany()
                        .HasForeignKey("FixedCostId");

                    b.HasOne("GeoServ.Api.Domain.Entities.PaymentMethod", "PaymentMethod")
                        .WithMany()
                        .HasForeignKey("PaymentMethodId");

                    b.HasOne("GeoServ.Api.Domain.Entities.User", "RegisteredByUser")
                        .WithMany()
                        .HasForeignKey("RegisteredByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GeoServ.Api.Domain.Entities.Responsible", "Responsible")
                        .WithMany()
                        .HasForeignKey("ResponsibleId");

                    b.HasOne("GeoServ.Api.Domain.Entities.ServiceOrder", "ServiceOrder")
                        .WithMany()
                        .HasForeignKey("ServiceOrderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Asset");

                    b.Navigation("Category");

                    b.Navigation("Check");

                    b.Navigation("DirectCost");

                    b.Navigation("FinancialAccount");

                    b.Navigation("FixedCost");

                    b.Navigation("PaymentMethod");

                    b.Navigation("RegisteredByUser");

                    b.Navigation("Responsible");

                    b.Navigation("ServiceOrder");
                });

            modelBuilder.Entity("GeoServ.Api.Domain.Entities.Asset", b =>
                {
                    b.HasOne("GeoServ.Api.Domain.Entities.Provider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("GeoServ.Api.Domain.Entities.Check", b =>
                {
                    b.HasOne("GeoServ.Api.Domain.Entities.Client", "ReceivedFromClient")
                        .WithMany()
                        .HasForeignKey("ReceivedFromClientId");

                    b.Navigation("ReceivedFromClient");
                });

            modelBuilder.Entity("GeoServ.Api.Domain.Entities.Client", b =>
                {
                    b.HasOne("GeoServ.Api.Domain.Entities.CompanyType", "CompanyType")
                        .WithMany("Clients")
                        .HasForeignKey("CompanyTypeId");

                    b.HasOne("GeoServ.Api.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("CompanyType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GeoServ.Api.Domain.Entities.Consumable", b =>
                {
                    b.HasOne("GeoServ.Api.Domain.Entities.ConsumableClass", "ConsumableClass")
                        .WithMany("Consumables")
                        .HasForeignKey("ConsumableClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GeoServ.Api.Domain.Entities.Provider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId");

                    b.HasOne("GeoServ.Api.Domain.Entities.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConsumableClass");

                    b.Navigation("Provider");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("GeoServ.Api.Domain.Entities.ConsumableClass", b =>
                {
                    b.HasOne("GeoServ.Api.Domain.Entities.ConsumableType", "ConsumableType")
                        .WithMany("ConsumableClasses")
                        .HasForeignKey("ConsumableTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConsumableType");
                });

            modelBuilder.Entity("GeoServ.Api.Domain.Entities.DirectCost", b =>
                {
                    b.HasOne("GeoServ.Api.Domain.Entities.DirectCostCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GeoServ.Api.Domain.Entities.Responsible", "PaidBy")
                        .WithMany()
                        .HasForeignKey("PaidById");

                    b.HasOne("GeoServ.Api.Domain.Entities.PaymentMethod", "PaymentMethod")
                        .WithMany()
                        .HasForeignKey("PaymentMethodId");

                    b.HasOne("GeoServ.Api.Domain.Entities.Provider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId");

                    b.HasOne("GeoServ.Api.Domain.Entities.User", "RegisteredByUser")
                        .WithMany()
                        .HasForeignKey("RegisteredByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GeoServ.Api.Domain.Entities.ServiceOrder", "ServiceOrder")
                        .WithMany("DirectCosts")
                        .HasForeignKey("ServiceOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GeoServ.Api.Domain.Entities.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId");

                    b.Navigation("Category");

                    b.Navigation("PaidBy");

                    b.Navigation("PaymentMethod");

                    b.Navigation("Provider");

                    b.Navigation("RegisteredByUser");

                    b.Navigation("ServiceOrder");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("GeoServ.Api.Domain.Entities.EmpresaConfiguracion", b =>
                {
                    b.HasOne("GeoServ.Api.Domain.Entities.Empresa", "Empresa")
                        .WithMany("Configuraciones")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("GeoServ.Api.Domain.Entities.FinancialAccount", b =>
                {
                    b.HasOne("GeoServ.Api.Domain.Entities.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("GeoServ.Api.Domain.Entities.FixedCost", b =>
                {
                    b.HasOne("GeoServ.Api.Domain.Entities.FixedCostCategory", "Category")
                        .WithMany("FixedCosts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("GeoServ.Api.Domain.Entities.FixedCostItem", b =>
                {
                    b.HasOne("GeoServ.Api.Domain.Entities.FixedCostCategory", "Category")
                        .WithMany("FixedCostItems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GeoServ.Api.Domain.Entities.Provider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId");

                    b.Navigation("Category");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("GeoServ.Api.Domain.Entities.FixedCostPayment", b =>
                {
                    b.HasOne("GeoServ.Api.Domain.Entities.FixedCostItem", "FixedCostItem")
                        .WithMany("Payments")
                        .HasForeignKey("FixedCostItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GeoServ.Api.Domain.Entities.PaymentMethod", "PaymentMethod")
                        .WithMany()
                        .HasForeignKey("PaymentMethodId");

                    b.Navigation("FixedCostItem");

                    b.Navigation("PaymentMethod");
                });

            modelBuilder.Entity("GeoServ.Api.Domain.Entities.Responsible", b =>
                {
                    b.HasOne("GeoServ.Api.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GeoServ.Api.Domain.Entities.ServiceOrder", b =>
                {
                    b.HasOne("GeoServ.Api.Domain.Entities.Client", "Client")
                        .WithMany("ServiceOrders")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GeoServ.Api.Domain.Entities.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GeoServ.Api.Domain.Entities.Project", "Project")
                        .WithMany("ServiceOrders")
                        .HasForeignKey("ProjectId");

                    b.HasOne("GeoServ.Api.Domain.Entities.ServiceType", "ServiceType")
                        .WithMany("ServiceOrders")
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GeoServ.Api.Domain.Entities.ServiceOrderStatus", "Status")
                        .WithMany("ServiceOrders")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Currency");

                    b.Navigation("Project");

                    b.Navigation("ServiceType");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("GeoServ.Api.Domain.Entities.ServiceOrderActivity", b =>
                {
                    b.HasOne("GeoServ.Api.Domain.Entities.ServiceOrder", "ServiceOrder")
                        .WithMany("Activities")
                        .HasForeignKey("ServiceOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceOrder");
                });

            modelBuilder.Entity("GeoServ.Api.Domain.Entities.ServiceOrderDistribution", b =>
                {
                    b.HasOne("GeoServ.Api.Domain.Entities.DistributionConcept", "DistributionConcept")
                        .WithMany("ServiceOrderDistributions")
                        .HasForeignKey("DistributionConceptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GeoServ.Api.Domain.Entities.ServiceOrder", "ServiceOrder")
                        .WithMany("Distributions")
                        .HasForeignKey("ServiceOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DistributionConcept");

                    b.Navigation("ServiceOrder");
                });

            modelBuilder.Entity("GeoServ.Api.Domain.Entities.ServiceOrderDocument", b =>
                {
                    b.HasOne("GeoServ.Api.Domain.Entities.ServiceOrder", "ServiceOrder")
                        .WithMany("Documents")
                        .HasForeignKey("ServiceOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GeoServ.Api.Domain.Entities.User", "UploadedBy")
                        .WithMany()
                        .HasForeignKey("UploadedById");

                    b.Navigation("ServiceOrder");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("GeoServ.Api.Domain.Entities.ServiceOrderObservation", b =>
                {
                    b.HasOne("GeoServ.Api.Domain.Entities.ServiceOrder", "ServiceOrder")
                        .WithMany("Observations")
                        .HasForeignKey("ServiceOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GeoServ.Api.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceOrder");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GeoServ.Api.Domain.Entities.ServiceOrderResponsible", b =>
                {
                    b.HasOne("GeoServ.Api.Domain.Entities.Responsible", "Responsible")
                        .WithMany()
                        .HasForeignKey("ResponsibleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GeoServ.Api.Domain.Entities.ServiceOrder", "ServiceOrder")
                        .WithMany("Responsibles")
                        .HasForeignKey("ServiceOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Responsible");

                    b.Navigation("ServiceOrder");
                });

            modelBuilder.Entity("GeoServ.Api.Domain.Entities.User", b =>
                {
                    b.HasOne("GeoServ.Api.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("GeoServ.Api.Domain.Entities.Client", b =>
                {
                    b.Navigation("ServiceOrders");
                });

            modelBuilder.Entity("GeoServ.Api.Domain.Entities.CompanyType", b =>
                {
                    b.Navigation("Clients");
                });

            modelBuilder.Entity("GeoServ.Api.Domain.Entities.ConsumableClass", b =>
                {
                    b.Navigation("Consumables");
                });

            modelBuilder.Entity("GeoServ.Api.Domain.Entities.ConsumableType", b =>
                {
                    b.Navigation("ConsumableClasses");
                });

            modelBuilder.Entity("GeoServ.Api.Domain.Entities.DistributionConcept", b =>
                {
                    b.Navigation("ServiceOrderDistributions");
                });

            modelBuilder.Entity("GeoServ.Api.Domain.Entities.Empresa", b =>
                {
                    b.Navigation("Configuraciones");
                });

            modelBuilder.Entity("GeoServ.Api.Domain.Entities.FixedCostCategory", b =>
                {
                    b.Navigation("FixedCostItems");

                    b.Navigation("FixedCosts");
                });

            modelBuilder.Entity("GeoServ.Api.Domain.Entities.FixedCostItem", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("GeoServ.Api.Domain.Entities.Project", b =>
                {
                    b.Navigation("ServiceOrders");
                });

            modelBuilder.Entity("GeoServ.Api.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("GeoServ.Api.Domain.Entities.ServiceOrder", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("DirectCosts");

                    b.Navigation("Distributions");

                    b.Navigation("Documents");

                    b.Navigation("Observations");

                    b.Navigation("Responsibles");
                });

            modelBuilder.Entity("GeoServ.Api.Domain.Entities.ServiceOrderStatus", b =>
                {
                    b.Navigation("ServiceOrders");
                });

            modelBuilder.Entity("GeoServ.Api.Domain.Entities.ServiceType", b =>
                {
                    b.Navigation("ServiceOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
